# Generated by Django 3.2.2 on 2021-07-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='followers_only',
            field=models.BooleanField(default=False),
        ),
    ]
